accounts:
- mes_euidos/accounts/*
- mes_euidos/controllers/accounts_controller.py
- mes_euidos/controllers/taxes_and_totals.py

stock:
- mes_euidos/stock/*
- mes_euidos/controllers/stock_controller.py
- mes_euidos/controllers/item_variant.py

assets:
- mes_euidos/assets/*

regional:
- mes_euidos/regional/*

selling:
- mes_euidos/selling/*
- mes_euidos/controllers/selling_controller.py

buying:
- mes_euidos/buying/*
- mes_euidos/controllers/buying_controller.py

support:
- mes_euidos/support/*

POS:
- pos*

ecommerce:
- mes_euidos/e_commerce/*

maintenance:
- mes_euidos/maintenance/*

manufacturing:
- mes_euidos/manufacturing/*

crm:
- mes_euidos/crm/*

HR:
- mes_euidos/hr/*

payroll:
- mes_euidos/payroll*

projects:
- mes_euidos/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['mes_euidos/**/*.py']
  all: ['!mes_euidos/**/test*.py']
